version: '3.3'

services:

  inventario:
      image: 
        fayu666/inventario
      ports: 
        - "80:5555"
      volumes:
        - /media/trabajo/Trabajo/Administracion/Stock.db:/inventario/bd/Stock.db

  ngrok:
    image: shkoliar/ngrok
    ports:
      - 4551:4551
    links:
      - inventario
    environment:
      - DOMAIN=inventario
      - PORT=5555

# datos ngrok
#           authtoken: 1qvuHs0Z1tT1ZIuzQ86JFLoaV4B_6ktDvT7BabQ1RUYboAkY7

# tunnels:
#   inventario:
#     proto: http
#     addr: 5555
#     auth: eze:eze

###############################################

# version: '2'
# services:

#   ngroktunnel:
#     build:
#       context: .
#     image: gtriggiano/ngrok-tunnel:development
#     ports:
#       - "4040:4040"
#     environment:
#       NGROK_REGION: eu
#       TARGET_HOST: testservice
#       TARGET_PORT: 5000
#     depends_on:
#       - testservice

#   testservice:
#     image: gtriggiano/dummy-http-service
#     ports:
#       - "8080:5000"
